name: Deploy ArgoCD

on:
  workflow_dispatch:

jobs:
  deploy-argocd:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}  # Replace with your actual secret
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}  # Replace with your actual secret
      AWS_REGION: "eu-west-1"
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Configure AWS Credentials 
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::688567261977:role/Github-Action-tf-eks
          aws-region: eu-west-1

      - name: Set up Terraform 
        uses: hashicorp/setup-terraform@v1
        with:
          terraform_wrapper: false

      - name: Terraform Init
        run: terraform init
        working-directory: ./argocd

      - name: Terraform Plan 
        run: terraform plan
        working-directory: ./argocd

      - name: Terraform Apply 
        run: terraform apply -auto-approve
        working-directory: ./argocd
      